apiVersion: v1
kind: ConfigMap
metadata:
  name: gpemu
  namespace: kube-system
data:
  config.json: |
    {
      "resourceName": "github.com/e-gpu",
      "socketName": "gpemu.sock",
      "numDevices": 2,
      "eGPUs": [{
        "hostPath": "/edev/egpu*",
        "containerPath": "/edev/egpu*",
        "permission": "r"
      }]
    }
